-- One statement per line. Run through the real PRQLite REPL by scripts/make-golden.mjs;
-- the TypeScript port must print byte-identical output for every line.
CREATE TABLE users (id INT, name TEXT, active BOOL);
INSERT INTO users VALUES (1, 'alice', true);
INSERT INTO users VALUES (2, 'bob', false);
INSERT INTO users VALUES (3, 'carol', true);
INSERT INTO users VALUES (4, 'dave', false);
SELECT * FROM users;
SELECT name, id FROM users;
SELECT active, name FROM users WHERE id = 3;
SELECT * FROM users WHERE id = 1 OR id = 3;
SELECT * FROM users WHERE id > 1 AND active = true;
SELECT * FROM users WHERE id = 1 AND active = true OR name = 'dave';
SELECT * FROM users WHERE (id = 1 OR id = 2) AND active = false;
SELECT * FROM users WHERE id <> 2;
SELECT * FROM users WHERE id != 2;
SELECT * FROM users WHERE id >= 3;
SELECT * FROM users WHERE id <= 2;
SELECT * FROM users WHERE id < 2;
SELECT * FROM users WHERE name > 'b';
SELECT * FROM users WHERE name <= 'bob';
SELECT * FROM users WHERE active = false;
SELECT * FROM users WHERE active != true;
SELECT * FROM users WHERE 1 = 1;
SELECT * FROM users WHERE id;
SELECT * FROM users WHERE id = 99;
SELECT * FROM users WHERE id = 99999999999;
INSERT INTO users VALUES (99999999999, 'big', true);
SELECT * FROM users ORDER BY id DESC LIMIT 1;
SELECT * FROM users garbage;
Select * from users;
UPDATE users;
SELECT * FROM users WHERE id = 1 AND;
SELECT * FROM users WHERE (id = 1;
SELECT * FROM users WHERE name = 'bob;
SELECT * FROM users WHERE id @ 1;
SELECT email FROM users;
SELECT * FROM users WHERE id = 'x';
SELECT * FROM users WHERE id AND active;
SELECT * FROM ghosts;
INSERT INTO users VALUES (5, 'eve');
INSERT INTO users VALUES ('x', 'eve', true);
CREATE TABLE users (x INT);
CREATE TABLE t (a INT, a TEXT);
CREATE INDEX idx ON users (id);
CREATE INDEX idx ON users (zz);
DELETE FROM users WHERE id;
BEGIN;
DELETE FROM users WHERE id = 2 OR id = 4;
SELECT * FROM users;
INSERT INTO users VALUES (9, 'zed', true);
SELECT * FROM users;
ROLLBACK;
SELECT * FROM users;
BEGIN;
BEGIN;
COMMIT;
COMMIT;
ROLLBACK;
DELETE FROM users WHERE id = 4 AND active = false;
SELECT * FROM users;
CREATE TABLE big (n INT, label TEXT, flag BOOL);
INSERT INTO big VALUES (1, 'row1', true);
INSERT INTO big VALUES (2, 'row2', false);
INSERT INTO big VALUES (3, 'row3', true);
INSERT INTO big VALUES (4, 'row4', false);
INSERT INTO big VALUES (5, 'row5', true);
INSERT INTO big VALUES (6, 'row6', false);
INSERT INTO big VALUES (7, 'row7', true);
INSERT INTO big VALUES (8, 'row8', false);
INSERT INTO big VALUES (9, 'row9', true);
INSERT INTO big VALUES (10, 'row10', false);
INSERT INTO big VALUES (11, 'row11', true);
INSERT INTO big VALUES (12, 'row12', false);
INSERT INTO big VALUES (13, 'row13', true);
INSERT INTO big VALUES (14, 'row14', false);
INSERT INTO big VALUES (15, 'row15', true);
INSERT INTO big VALUES (16, 'row16', false);
INSERT INTO big VALUES (17, 'row17', true);
SELECT n FROM big WHERE n > 13;
DELETE FROM big WHERE n < 10;
SELECT * FROM big;
INSERT INTO big VALUES (18, 'row18', true);
SELECT n, label FROM big WHERE n >= 16;
